version: '3'
services:
  qcobjects:
    image: qcobjects_newapp:latest
    hostname: qcobjects_newapp
    command: ["npm","run", "start"]
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 8080
      - 8443
      - 10300
    ports:
      - 8080:8080
      - 8443:8443
      - 10300:10300
    env_file:
      - ./.env
